### PR TITLE
Remove dependency on requests module

### LINKED ISSUE #2: Running openshift-applier fails: missing requests
Running the _apply.yml_ playbook fails as openshift-applier requires the requests module installed:

screen shot 2018-08-31 at 11 31 17

### PR DESCRIPTION
**Pull request by martineg**
Install requests module required by filter-plugins in openshift-applier role

Fixes #2

### CODE REVIEW

**Comment by etsauer** [comment]
@logandonley @oybed @pcarney8

**Comment by sabre1041** [comment]
@martineg @etsauer @oybed @pcarney8 @logandonley We removed dependency on requests package  in https://github.com/redhat-cop/openshift-applier/pull/50

**Comment by oybed** [comment]
As @sabre1041 said, this is not needed starting with `openshift-applier` release `v2.0.2` https://github.com/redhat-cop/openshift-applier/releases/tag/v2.0.2

**Comment by etsauer** [comment]
@martineg sounds like, rather than adding requests.. you can update `step1.md` to use `v2.0.2` instead of `v2.0.0`

**Pull request merged**
